### ISSUE TITLE
pad3: /etc/product is 600

### ISSUE THREAD

**Issue by ZeroChaos-** [pwnieexpress/pwn_pad_sources#52]
/etc/product has the wrong mode set on the pad3:

-rw-------. 1 root root 8 May 28 10:04 /etc/product

it should be 644 like on the other sensors.

Where do I find the kali chroot creation scripts to fix this?

**Comment by tmossey** [comment]
This is where /etc/product is set, so it's probably where this should be handled.

https://github.com/pwnieexpress/pwnix_chef/blob/develop/support_scripts/system-setup.sh

**Comment by ZeroChaos-** [comment]
fixed by https://github.com/pwnieexpress/pwnix_chef/pull/163 or by not bypassing the proper codepath for creating /etc/product.
